strategy:
  matrix:
    region: [us-east-1, us-west-2, eu-west-1]

steps:
  ...
  - name: Configure AWS
    uses: aws-actions/configure-aws-credentials@v2
    with:
      aws-region: ${{ matrix.region }}
